const variant = document.body.dataset.variant;
const meta = {
  a: { label: 'A / CLEAN PREMIUM', kicker: 'CLEANHOUSE / HOME', intro: '입주·이사 전 공간을 정돈하고, 비용과 과정까지 투명하게 안내합니다.' },
  b: { label: 'B / EDITORIAL TRUST', kicker: 'A QUIET STANDARD FOR A NEW HOME', intro: '정리된 공간, 먼저 안내하는 비용. 집의 첫 장면을 클린하우스가 만듭니다.' },
  c: { label: 'C / RESULT FIRST', kicker: 'RESULTS, BEFORE PROMISES', intro: '입주·이사청소의 결과를 먼저 보여드리고, 필요한 견적만 정확하게 안내합니다.' },
};
const m = meta[variant];
const aPriceRows = '<div><span>20평 이하</span><strong>180,000원</strong></div><div><span>21~30평</span><strong>230,000원</strong></div><div><span>31~40평</span><strong>280,000원</strong></div><div><span>41~50평</span><strong>330,000원</strong></div><div><span>51평 이상</span><strong>상담</strong></div>';
const bPriceRows = '<div><b>21 — 30평</b><strong>230,000<span>원</span></strong></div><div><b>31 — 40평</b><strong>280,000<span>원</span></strong></div><div><b>41 — 50평</b><strong>330,000<span>원</span></strong></div><div><b>51평 이상</b><strong>상담</strong></div>';
const nav = `<div class="prototype-bar"><span>${m.label}</span><nav aria-label="디자인 방향"><a class="${variant === 'a' ? 'is-active' : ''}" href="./design-a.html">A</a><a class="${variant === 'b' ? 'is-active' : ''}" href="./design-b.html">B</a><a class="${variant === 'c' ? 'is-active' : ''}" href="./design-c.html">C</a></nav><a class="back-link" href="./index.html">비교 화면으로</a></div>`;
const header = `<header class="site-header"><a class="brand" href="./index.html">CLEAN<br /><span>HOUSE</span></a><p>입주·이사청소<br />서울·경기 중심</p><a class="header-link" href="#estimate">견적 요청 <span>↗</span></a></header>`;
const cta = '<a class="primary-cta" href="#pricing">청소 견적 요청하기 <span>↗</span></a>';
const aMarkup = `<main class="a-page"><section class="a-hero" id="estimate"><div class="a-hero-copy"><p class="eyebrow">${m.kicker}</p><h1>새집의 시작을<br />더 깨끗하고 편안하게</h1><p class="hero-intro">${m.intro}</p>${cta}<p class="microcopy">평수와 날짜를 알려주시면 기본 비용부터 안내합니다.</p></div><figure class="a-hero-visual"><div class="mock-label">DESIGN MOCK ASSET</div><div class="hero-image"></div><figcaption><span>01</span> 공간의 시작을 정돈하는 시간</figcaption></figure></section><section class="a-pricing" id="pricing"><div class="a-pricing-intro"><p class="eyebrow">02 / PRICE SUMMARY</p><h2>청소 비용,<br /><em>먼저 확인하세요.</em></h2><p>평수별 기본 가격을 먼저 공개합니다.<br />추가 비용이 필요한 경우 작업 전에 안내합니다.</p></div><div class="a-price-table">${aPriceRows}</div></section><section class="a-trust"><p class="eyebrow">03 / TRUST IN NUMBERS</p><div class="a-trust-center"><strong>1,200<span>+</span></strong><p>누적 입주·이사청소 진행</p></div><p class="a-trust-caption">한 번의 청소가 아니라<br />쌓아온 기준으로 답합니다.</p></section><section class="a-cases"><div class="a-cases-title"><p class="eyebrow">04 / BEFORE & AFTER</p><h2>달라진 공간은<br /><em>설명보다 선명합니다.</em></h2><p>실제 Before / After 자료 공개 전,<br />구조 검증을 위한 디자인 목업입니다.</p></div><div class="a-case-spread"><div class="case-image case-image--before"><span>BEFORE</span></div><div class="case-image case-image--after"><span>AFTER</span><div class="mock-label">DESIGN MOCK ASSET</div></div><div class="case-divider">→</div></div></section></main>`;
const bMarkup = `<main class="b-page"><section class="b-hero" id="estimate"><div class="b-hero-stamp">01<br /><span>THE FIRST CLEAN START</span></div><div class="b-hero-image"><div class="mock-label">DESIGN MOCK ASSET</div></div><div class="b-hero-copy"><p class="eyebrow">${m.kicker}</p><h1>새집의 시작을<br />더 깨끗하고 편안하게</h1><p>${m.intro}</p>${cta}<small>평수와 날짜를 알려주시면 기본 비용부터 안내합니다.</small></div></section><section class="b-pricing" id="pricing"><div class="b-price-index"><p class="eyebrow">02 / PRICE SUMMARY</p><p>먼저 보이는 비용,<br />나중에 없는 놀람.</p><span>01 — 05</span></div><div class="b-price-feature"><strong>180<span>,000원</span></strong><em>20평 이하</em><small>기본 가격부터 투명하게<br />추가 비용은 작업 전에 안내</small></div><div class="b-price-list">${bPriceRows}</div></section><section class="b-trust"><div class="b-trust-image"><div class="mock-label">DESIGN MOCK ASSET</div></div><div class="b-trust-copy"><p class="eyebrow">03 / TRUST IN NUMBERS</p><strong>1,200<span>+</span></strong><p>누적 입주·이사청소 진행</p><small>공간별 체계적인 청소<br />고객 검수 및 미흡 부분 보완</small></div></section><section class="b-cases"><div class="b-case-heading"><p class="eyebrow">04 / BEFORE & AFTER</p><h2>달라진 공간은<br /><em>설명보다 선명합니다.</em></h2></div><p class="b-case-note">실제 Before / After 자료 공개 전,<br />구조 검증을 위한 디자인 목업입니다.</p><div class="b-case-canvas"><div class="b-case-before"><span>BEFORE / 01</span></div><div class="b-case-after"><div class="mock-label">DESIGN MOCK ASSET</div><span>AFTER / 01</span></div><div class="b-case-arrow">↗</div></div></section></main>`;
const cMarkup = `<main class="c-page"><section class="c-hero" id="estimate"><div class="c-result-image"><div class="mock-label">DESIGN MOCK ASSET</div><span>AFTER / LIVING SPACE</span></div><div class="c-hero-card"><p class="eyebrow">${m.kicker}</p><h1>새집의 시작을<br />더 깨끗하고 편안하게</h1><p>${m.intro}</p>${cta}</div><p class="c-hero-index">01 / RESULT FIRST</p></section><section class="c-pricing" id="pricing"><div class="c-price-photo"></div><div class="c-price-panel"><p class="eyebrow">02 / PRICE SUMMARY</p><h2>청소 비용,<br /><em>먼저 확인하세요.</em></h2><div class="c-price-ribbon">20평 이하 <strong>180,000원</strong></div><div class="c-price-foot">21~30평 230,000원<br />31~40평 280,000원<br />41~50평 330,000원<br />51평 이상 상담</div><p>추가 비용이 필요한 경우 작업 전에 안내합니다.</p></div></section><section class="c-proof"><div class="c-proof-photo"></div><div class="c-proof-number"><p class="eyebrow">03 / TRUST IN NUMBERS</p><strong>1,200<span>+</span></strong><p>누적 입주·이사청소 진행</p></div><div class="c-proof-note">고객 검수 및<br />미흡 부분 보완</div></section><section class="c-cases"><div class="c-case-meta"><p class="eyebrow">04 / BEFORE & AFTER</p><h2>달라진 공간은<br /><em>설명보다 선명합니다.</em></h2><p>실제 Before / After 자료 공개 전,<br />구조 검증을 위한 디자인 목업입니다.</p></div><div class="c-case-before"><span>BEFORE</span></div><div class="c-case-after"><div class="mock-label">DESIGN MOCK ASSET</div><span>AFTER</span></div><div class="c-case-arrow">→</div></section></main>`;
document.querySelector('#app').innerHTML = nav + header + (variant === 'a' ? aMarkup : variant === 'b' ? bMarkup : cMarkup) + '<footer class="footer"><span>CLEANHOUSE</span><span>DESIGN PROTOTYPE · A/B/C COMPARISON</span></footer>';
